site_name: "SploitKit - Toolkit for building Metasploit-like consoles"
repo_url: https://github.com/dhondta/sploitkit
site_author: dhondta
docs_dir: docs
nav:
  - Introduction: index.md
  - Design: design.md
  - Classes: classes.md
  - Classes:
    - Entity: classes/entity.md
    - Console: classes/console.md
    - Command: classes/command.md
    - Module: classes/module.md
    - Datastore: classes/datastore.md
  - 'Real-life examples':
    - 'DroneSploit': examples/dronesploit.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - codehilite:
      linenums: true
  - pymdownx.details
